language: php
dist: trusty

jobs:
  fast_finish: true
  allow_failures:
    - php: "nightly"
  include:
    - php: "5.5"
    - php: "5.6"
    - php: "7.0"
    - php: "7.1"
    - php: "7.2"
    - php: "7.3"
    - php: "7.4"
    - php: "nightly"

cache:
  apt: true
  directories:
    - $HOME/.composer/cache
    - vendor

install:
  - composer install --no-interaction --prefer-source

# vim:ts=2:sw=2:et
